name: Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'nginx.conf'
      - 'package.json'
      - 'vite.config.*'
      - 'src/**'
      - '.github/workflows/docker-image.yml'
  
  # Build image automatically when a GitHub Release is published (ensures versioned tag published)
  release:
    types: [ published ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bugs-buzzy/bugsbuzzy-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate production env file
        run: |
          echo "Creating .env.production with injected secrets (blank if not set)."
          cat > .env.production <<'EOF'
          APP_ENV=production
          VITE_API_BASE_URL=${{ secrets.PROD_VITE_API_BASE_URL }}
          VITE_SENTRY_DSN=${{ secrets.PROD_VITE_SENTRY_DSN }}
          VITE_ANALYTICS_KEY=${{ secrets.PROD_VITE_ANALYTICS_KEY }}
          VITE_FEATURE_FLAGS_KEY=${{ secrets.PROD_VITE_FEATURE_FLAGS_KEY }}
          EOF
          echo "Created .env.production (contents redacted)."
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image digest
        run: echo "Image digest ${{ steps.meta.outputs.digest }}"
